import * as fs from "node:fs";
import * as path from "node:path";

import { IRequirementGraphRepository } from "../application/ports/IRequirementGraphRepository";
import { splitDependencies } from "../domain/RequirementGraph";
import { parseSpec } from "../domain/SpecParser";
import { parseMatrixDependencies } from "../domain/TraceabilityFormat";
import { CAPABILITIES_DIR } from "./ChangeWorkspace";

// Where capability specs live is the change workspace's fact, stated once there.
export { CAPABILITIES_DIR } from "./ChangeWorkspace";

const REQ_ID = /^REQ-[A-Za-z0-9.]+$/;

/**
 * Read every capability spec and return what each requirement declares.
 *
 * A capability whose spec does not parse is `validate`'s problem to report,
 * not this function's to crash on.
 */
export function readDeclaredDependencies(projectDir: string): Record<string, string[]> {
  // The matrix first, then the capability specs on top: a spec is hand-written
  // by the project, the matrix line was generated by the last `expand`, so the
  // hand-written statement wins.
  const declared: Record<string, string[]> = readMatrixDependencies(projectDir);

  const root = path.join(projectDir, CAPABILITIES_DIR);
  if (!fs.existsSync(root)) return declared;

  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const specPath = path.join(root, entry.name, "spec.md");
    if (!fs.existsSync(specPath)) continue;

    for (const [id, deps] of readSpecDependencies(specPath)) declared[id] = deps;
  }
  return declared;
}

/**
 * The dependencies a domain pack declared, as `expand` wrote them (B1).
 *
 * A pack's requirements do not arrive as capability specs — the capability
 * document each pack ships is its own template, and the requirements themselves
 * land in the traceability matrix. So a pack's `depends_on` is written beside
 * the matrix and read back from there.
 *
 * A capability spec wins on a conflict: it is hand-written by the project,
 * while the matrix line was generated by the last `expand`.
 */
function readMatrixDependencies(projectDir: string): Record<string, string[]> {
  const matrix = path.join(projectDir, "docs", "specs", "traceability.md");
  if (!fs.existsSync(matrix)) return {};
  try {
    return parseMatrixDependencies(fs.readFileSync(matrix, "utf8"));
  } catch {
    return {};
  }
}

function readSpecDependencies(specPath: string): Array<[string, string[]]> {
  let parsed: { requirements?: Array<{ id?: string; trace?: Record<string, string> }> };
  try {
    parsed = parseSpec(fs.readFileSync(specPath, "utf8"));
  } catch {
    return [];
  }

  const found: Array<[string, string[]]> = [];
  for (const req of parsed.requirements ?? []) {
    const id = req.id ? String(req.id).toUpperCase() : "";
    if (!REQ_ID.test(id)) continue;
    const raw = req.trace?.depends;
    if (!raw) continue;
    const deps = splitDependencies(raw);
    if (deps.length > 0) found.push([id, deps]);
  }
  return found;
}
/** Reads the declarations straight off the project's capability specs. */
export class DiskRequirementGraphRepository implements IRequirementGraphRepository {
  public readDeclaredDependencies(projectDir: string): Record<string, string[]> {
    return readDeclaredDependencies(projectDir);
  }
}
