asyncapi: "2.6.0"
info:
  title: "{{PROVIDER_SERVICE}} Events"
  version: "1.0.0"
  description: |
    AsyncAPI contract for events published by {{PROVIDER_SERVICE}}.
    Generated by create-spec-driven-app from the contracts pack.
channels:
  {{PROJECT_SLUG}}/events:
    subscribe:
      summary: Domain events published by {{PROVIDER_SERVICE}}
      message:
        name: DomainEvent
        payload:
          type: object
          properties:
            eventId:
              type: string
              format: uuid
            occurredAt:
              type: string
              format: date-time
            eventType:
              type: string
