openapi: "3.1.0"
info:
  title: "{{PROVIDER_SERVICE}} API"
  version: "1.0.0"
  description: |
    REST API contract for {{PROJECT_NAME}}.
    Generated by create-spec-driven-app from the contracts pack.
    Replace stub paths with real endpoint definitions.
servers:
  - url: "https://api.{{PROJECT_SLUG}}.example.com/v1"
    description: Production
  - url: "http://localhost:8080/v1"
    description: Local development
paths:
  /health:
    get:
      operationId: getHealth
      summary: Health check
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
