APP_ENV=prod
PROJECT_SLUG={{PROJECT_SLUG}}

DATABASE_ENGINE={{DATABASE_ENGINE}}
DATABASE_IMAGE={{DATABASE_IMAGE}}
DATABASE_HOST={{DATABASE_HOST}}
DATABASE_PORT={{DATABASE_PORT_PROD}}
DATABASE_CONTAINER_PORT={{DATABASE_CONTAINER_PORT}}
DATABASE_NAME={{DATABASE_NAME_PROD}}
DATABASE_USER={{DATABASE_USER}}
DATABASE_PASSWORD={{DATABASE_PASSWORD}}
DATABASE_URL={{DATABASE_URL_PROD}}

POSTGRES_DB={{DATABASE_NAME_PROD}}
POSTGRES_USER={{DATABASE_USER}}
POSTGRES_PASSWORD={{DATABASE_PASSWORD}}
