# Application variables for the feature environment.
APP_ENV=feature
PROJECT_SLUG={{PROJECT_SLUG}}

DATABASE_ENGINE={{DATABASE_ENGINE}}
DATABASE_HOST={{DATABASE_HOST}}
DATABASE_PORT={{DATABASE_PORT_FEATURE}}
DATABASE_NAME={{DATABASE_NAME_FEATURE}}
DATABASE_USER={{DATABASE_USER}}
DATABASE_PASSWORD={{DATABASE_PASSWORD}}
DATABASE_URL={{DATABASE_URL_FEATURE}}
