# Copy one environment file to `.env` or set `APP_ENV` before running Docker Compose.
APP_ENV={{DEFAULT_ENV}}
PROJECT_SLUG={{PROJECT_SLUG}}

DATABASE_ENGINE={{DATABASE_ENGINE}}
DATABASE_IMAGE={{DATABASE_IMAGE}}
DATABASE_HOST={{DATABASE_HOST}}
DATABASE_PORT={{DATABASE_PORT}}
DATABASE_CONTAINER_PORT={{DATABASE_CONTAINER_PORT}}
DATABASE_NAME={{DATABASE_NAME_DEV}}
DATABASE_USER={{DATABASE_USER}}
DATABASE_PASSWORD={{DATABASE_PASSWORD}}
DATABASE_URL={{DATABASE_URL_DEV}}

POSTGRES_DB={{DATABASE_NAME_DEV}}
POSTGRES_USER={{DATABASE_USER}}
POSTGRES_PASSWORD={{DATABASE_PASSWORD}}
