# Application variables for the prod environment.
# WARNING: Replace placeholder values before deploying.
# Inject DATABASE_PASSWORD and DATABASE_URL via CI secrets or a secrets manager.
APP_ENV=prod
PROJECT_SLUG={{PROJECT_SLUG}}

DATABASE_ENGINE={{DATABASE_ENGINE}}
DATABASE_HOST={{DATABASE_HOST}}
DATABASE_PORT={{DATABASE_PORT_PROD}}
DATABASE_NAME={{DATABASE_NAME_PROD}}
DATABASE_USER={{DATABASE_USER}}
DATABASE_PASSWORD={{DATABASE_PASSWORD}}
DATABASE_URL={{DATABASE_URL_PROD}}
