# Generated by `create-spec-driven-app ci init --provider azure`
# Spec-Driven Development gate for Azure Pipelines.
trigger:
  branches:
    include: [main]
pr:
  branches:
    include: ['*']

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: Use Node.js 20

  - script: npx create-spec-driven-app@{{CSDA_VERSION}} validate . --strict-tdd
    displayName: Validate specs (strict TDD)

  - script: npx create-spec-driven-app@{{CSDA_VERSION}} plan --project-dir . --format json > $(Build.ArtifactStagingDirectory)/spec-plan.json
    condition: always()
    displayName: Export pending-work plan

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/spec-plan.json
      artifactName: spec-plan
