# Generated by `create-spec-driven-app ci init --provider github`
# Spec-Driven Development gate: no PR merges if a requirement loses its
# feature file, its test artifact, or its traceability row.
name: Spec gate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  spec-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Validate specs (strict TDD)
        run: npx create-spec-driven-app@{{CSDA_VERSION}} validate . --strict-tdd
      - name: Export pending-work plan
        if: always()
        run: npx create-spec-driven-app@{{CSDA_VERSION}} plan --project-dir . --format json > spec-plan.json
      - name: Upload plan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spec-plan
          path: spec-plan.json
