# Generated by `create-spec-driven-app ci init --provider gitlab`
# Spec-Driven Development gate for GitLab CI. If your project already has a
# .gitlab-ci.yml, paste the `spec-gate` job into it instead.
spec-gate:
  image: node:20
  stage: test
  script:
    - npx create-spec-driven-app@{{CSDA_VERSION}} validate . --strict-tdd
    - npx create-spec-driven-app@{{CSDA_VERSION}} plan --project-dir . --format json > spec-plan.json
  artifacts:
    when: always
    paths:
      - spec-plan.json
