# Generated by `specgate ci init --provider gitlab`
# Spec-Driven Development gate for GitLab CI. If your project already has a
# .gitlab-ci.yml, paste the `spec-gate` job into it instead.
spec-gate:
  image: node:22
  stage: test
  script:
    - npx specgate@{{SPECGATE_VERSION}} validate . --strict-tdd
    # Supply-chain gate: fails when rendered pack content no longer matches the
    # digest pinned in .specops.lock. Skipped when no packs are installed.
    - >
      if [ -f .specops.lock ]; then
        npx specgate@{{SPECGATE_VERSION}} validate . --against-lock;
      else
        echo "No .specops.lock — no packs installed, nothing to check.";
      fi
    - npx specgate@{{SPECGATE_VERSION}} plan --project-dir . --format json > spec-plan.json
  artifacts:
    when: always
    paths:
      - spec-plan.json
