// Generated by `specgate ci init --provider jenkins`
// Spec-Driven Development gate for Jenkins (declarative pipeline).
// If your project already has a Jenkinsfile, paste the 'Spec gate' stage in.
pipeline {
    agent {
        docker { image 'node:22' }
    }
    stages {
        stage('Spec gate') {
            steps {
                sh 'npx @rsaglobaltech/specgate@{{SPECGATE_VERSION}} validate . --strict-tdd'
            }
        }
        // Supply-chain gate: fails when rendered pack content no longer
        // matches the digest pinned in .specops.lock. Skipped when the
        // project installs no packs.
        stage('Pack drift') {
            steps {
                sh '''
                    if [ -f .specops.lock ]; then
                        npx @rsaglobaltech/specgate@{{SPECGATE_VERSION}} validate . --against-lock
                    else
                        echo "No .specops.lock — no packs installed, nothing to check."
                    fi
                '''
            }
        }
    }
    post {
        always {
            sh 'npx @rsaglobaltech/specgate@{{SPECGATE_VERSION}} plan --project-dir . --format json > spec-plan.json || true'
            archiveArtifacts artifacts: 'spec-plan.json', allowEmptyArchive: true
        }
    }
}
