// Generated by `create-spec-driven-app ci init --provider jenkins`
// Spec-Driven Development gate for Jenkins (declarative pipeline).
// If your project already has a Jenkinsfile, paste the 'Spec gate' stage in.
pipeline {
    agent {
        docker { image 'node:20' }
    }
    stages {
        stage('Spec gate') {
            steps {
                sh 'npx create-spec-driven-app@{{CSDA_VERSION}} validate . --strict-tdd'
            }
        }
    }
    post {
        always {
            sh 'npx create-spec-driven-app@{{CSDA_VERSION}} plan --project-dir . --format json > spec-plan.json || true'
            archiveArtifacts artifacts: 'spec-plan.json', allowEmptyArchive: true
        }
    }
}
