#!/usr/bin/env node
"use strict";

/**
 * Generates `docs/specs/agent-contract.md` from the source, never by hand.
 *
 * ADR-0017 promised a contract document plus snapshot tests so "the published
 * document cannot silently drift". A hand-written catalogue of diagnostic codes
 * is out of date the first time someone adds a check and forgets — which is
 * exactly the failure mode this repository has been correcting all week.
 *
 * The code catalogue is harvested from the calls themselves. The command table
 * is declared here because a command's null-shape is a design decision, not
 * something to infer; `tests/unit/agent-contract.test.ts` runs every row and
 * fails if a command's real output stops matching what this table claims.
 *
 *   npm run docs:agent-contract        # rewrite the document
 *   node --test dist/tests/unit/agent-contract.test.js   # fail if it is stale
 */

const fs = require("node:fs");
const path = require("node:path");

const { EXIT } = require("./lib/agent");
const { jsonContractRows } = require("./lib/surface");

/**
 * The repository root, found by walking up to the package.json. Hardcoding a
 * `..` count breaks depending on whether this runs from `scripts/` or from the
 * compiled `dist/scripts/` — the first version silently wrote the document into
 * `dist/`.
 */
function repoRoot() {
  let dir = __dirname;
  while (!fs.existsSync(path.join(dir, "package.json"))) {
    const parent = path.dirname(dir);
    if (parent === dir) throw new Error("package.json not found above " + __dirname);
    dir = parent;
  }
  return dir;
}

const ROOT = repoRoot();
const OUTPUT = path.join(ROOT, "docs/specs/agent-contract.md");

/**
 * Every command that speaks JSON, with the key its document carries, derived
 * from the one surface declaration.
 *
 * It was a second hand-written table here, which is how a command could speak
 * the contract without the document knowing. `tests/unit/agent-contract.test.ts`
 * runs every row and fails if a command's real output stops matching it.
 */
const COMMANDS = jsonContractRows();

/** Source files whose diagnostics form the public code catalogue. */
const SOURCE_GLOBS = [
  "scripts/validate_specs.ts",
  "scripts/doctor.ts",
  "scripts/done.ts",
  "scripts/change/cli.ts",
  "scripts/change/delta.ts",
  "scripts/change/archive.ts",
  "scripts/change/instructions.ts",
  "scripts/specops/against_lock.ts",
  "scripts/specops/contribute.ts",
];

/**
 * Harvest `error("code", …)` / `warning("code", …)` / `diagnostic(sev, "code", …)`
 * from the source. Anything the code emits is in the catalogue by construction.
 */
function harvestCodes() {
  const byArea = new Map();
  for (const rel of SOURCE_GLOBS) {
    const file = path.join(ROOT, rel);
    if (!fs.existsSync(file)) continue;
    const source = fs.readFileSync(file, "utf8");
    const codes = new Set<string>();
    // `fail(` is validate's own reporter; it takes the code first too.
    for (const m of source.matchAll(/\b(?:error|warning|info|fail)\(\s*"([a-z][a-z0-9_]*)"/g)) {
      codes.add(m[1]);
    }
    for (const m of source.matchAll(/\bdiagnostic\(\s*[^,]+,\s*"([a-z][a-z0-9_]*)"/g)) {
      codes.add(m[1]);
    }
    // Template-literal codes are computed, not literal — record the family.
    for (const m of source.matchAll(/\b(?:error|warning)\(\s*`([a-z][a-z0-9_]*)\$\{/g)) {
      codes.add(`${m[1]}*`);
    }
    if (codes.size > 0) byArea.set(rel, [...codes].sort());
  }
  return byArea;
}

function table(rows, headers) {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `|${headers.map(() => "---").join("|")}|`;
  return [head, sep, ...rows.map((r) => `| ${r.join(" | ")} |`)].join("\n");
}

function render() {
  const codes = harvestCodes();
  const codeRows = [];
  for (const [file, list] of codes) {
    for (const code of list) codeRows.push([`\`${code}\``, `\`${file}\``]);
  }

  return `# The agent contract

<!-- GENERATED by scripts/gen_agent_contract.ts — do not edit by hand.
     Run \`npm run docs:agent-contract\` after changing a command's JSON shape or
     adding a diagnostic code. tests/unit/agent-contract.test.ts fails when this
     file is stale. -->

How a machine drives this CLI. The rules are fixed by
[ADR-0017](adr/0017-agent-json-contract.md); this document is generated from the
source so it cannot drift from it.

## The rules

1. **One JSON document per invocation.** In \`--json\` mode stdout carries exactly
   one JSON document. Prose, progress and warnings go to stderr, so
   \`cmd --json 2>/dev/null | jq .\` always parses.
2. **One diagnostic envelope**, everywhere:

   \`\`\`json
   {
     "severity": "error" | "warning" | "info",
     "code": "snake_case_stable_string",
     "message": "human sentence",
     "target": "the thing at fault (optional)",
     "fix": "one actionable sentence or command (optional)",
     "file": "relative/path.md (optional)",
     "line": 42
   }
   \`\`\`

   Branch on \`code\`, never on \`message\`. \`message\` is prose and may be reworded;
   \`code\` is the published surface.
3. **Failure carries the command's null-shape.** A failure prints
   \`{ ...nullShape, "status": [diagnostic] }\` and exits 1 — never bare stderr,
   never a partial document. A consumer never has to tell "it failed" apart from
   "it printed nothing".
4. **camelCase everywhere** in command output. (The on-disk formats are not
   command output: \`pack.yaml\` keeps \`schema_version\` and \`.specops.lock\` keeps
   \`pack_id\`.)
5. **\`--json\` and \`--format json\` are the same flag.** The second spelling
   predates the contract and keeps working.

## Exit codes

${table(
  [
    ["Success, including advisory warnings", `\`${EXIT.OK}\``],
    ["Command failure — one JSON document with `status`", `\`${EXIT.FAILURE}\``],
    ["Gate failure (`validate`, `doctor`, `change validate`)", `\`${EXIT.FAILURE}\``],
    ["Usage error — unknown flag, missing or malformed argument", `\`${EXIT.USAGE}\``],
    ["Required script missing (a broken installation)", `\`${EXIT.MISSING_PREREQUISITE}\``],
    ["Cancelled by the user", `\`${EXIT.CANCELLED}\``],
  ],
  ["Situation", "Exit"]
)}

A gate command exits ${EXIT.FAILURE} when it *finds* something, which is not the
same as failing to run. The \`status\` array tells the two apart: a gate that could
not run reports an \`error\` about itself.

## Commands

${table(
  COMMANDS.map((c) => [`\`csda ${c.command}\``, `\`${c.nullShapeKey}\``, c.gate ? "yes" : "no"]),
  ["Command", "Document key", "Gate"]
)}

The document key is what the payload carries on success and what is set to
\`null\` on failure. Every document also carries \`status\`: an array of
diagnostics, empty when there is nothing to report.

## Diagnostic codes

Harvested from the source. A trailing \`*\` marks a family whose suffix is
computed — \`strict_tdd_*\` covers \`strict_tdd_1\` through \`strict_tdd_3\`.

${table(codeRows, ["Code", "Emitted by"])}

## Worked example

\`\`\`bash
csda change instructions specs --json 2>/dev/null | jq -r '.instructions.rules[]'
\`\`\`

An agent that reads \`fix\` self-corrects; one that reads only \`message\` retries
the same mistake. That is why a check without a \`fix\` is treated as unfinished.
`;
}

function main() {
  const check = process.argv.includes("--check");
  const rendered = render();
  if (check) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, "utf8") : "";
    if (current !== rendered) {
      process.stderr.write(
        "docs/specs/agent-contract.md is stale. Run: npm run docs:agent-contract\n"
      );
      process.exit(EXIT.FAILURE);
    }
    process.stdout.write("agent-contract.md is up to date\n");
    return;
  }
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, rendered, "utf8");
  process.stdout.write(`Wrote ${path.relative(ROOT, OUTPUT)}\n`);
}

if (require.main === module) main();

module.exports = { render, harvestCodes, COMMANDS, OUTPUT };
