/**
 * Interactive wizard for `init` — collects the same keys a project.yaml
 * would provide, with sensible defaults, so `csda init` works with zero
 * flags on a terminal.
 *
 * Pure helpers (slugify, defaultAnswers, validateAnswer, renderConfigYaml,
 * WIZARD_FIELDS) are exported for unit tests; only runInitWizard reads
 * from stdin.
 */

import * as readline from "node:readline/promises";

const SLUG_RE = /^[a-z0-9][a-z0-9-]*$/;

export function slugify(name) {
  const slug = String(name || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "my-spec-driven-app";
}

export const WIZARD_FIELDS = [
  {
    key: "PROJECT_NAME",
    question: "Project name",
    def: () => "My Spec-Driven App",
  },
  {
    key: "PROJECT_SLUG",
    question: "Project slug",
    def: (answers) => slugify(answers.PROJECT_NAME),
    validate: (value) =>
      SLUG_RE.test(value)
        ? null
        : "Use lowercase letters, numbers, and dashes (example: my-project).",
  },
  {
    key: "PROJECT_TYPE",
    question: "Project type",
    choices: ["backend", "frontend", "mobile"],
    def: () => "backend",
  },
  {
    key: "DOMAIN",
    question: "Business domain (e.g. parking operations)",
    def: () => "general",
  },
  {
    key: "STACK",
    question: "Tech stack",
    def: () => "Java 21, Spring Boot 3.x, PostgreSQL",
  },
  {
    key: "API_STYLE",
    question: "API style",
    def: () => "REST with DTO boundaries",
  },
  {
    key: "TESTING",
    question: "Testing toolchain",
    def: () => "JUnit 5, Testcontainers, Cucumber",
  },
  {
    key: "MODULES",
    question: "Optional modules (auth,dashboard,billing — empty for none)",
    def: () => "",
  },
];

export function validateAnswer(field, value) {
  if (field.choices && !field.choices.includes(value)) {
    return `Choose one of: ${field.choices.join(", ")}.`;
  }
  if (field.validate) {
    return field.validate(value);
  }
  return null;
}

/** Answers produced by accepting every wizard default (`init --yes`). */
export function defaultAnswers() {
  const answers = {};
  for (const field of WIZARD_FIELDS) {
    answers[field.key] = field.def(answers);
  }
  return answers;
}

function yamlScalar(value) {
  return /[:#'"{}[\]&*!|>%@`]/.test(value) ? JSON.stringify(value) : value;
}

/**
 * Serialize wizard answers as a project.yaml so the run is reproducible
 * with `init --config project.yaml`.
 */
export function renderConfigYaml(answers) {
  const lines = [
    "# Generated by `csda init` (interactive wizard).",
    "# Reproduce this project with:",
    "#   csda init --config project.yaml --out <parent-dir>",
  ];
  for (const field of WIZARD_FIELDS) {
    const value = answers[field.key];
    if (value === undefined || value === "") continue;
    lines.push(`${field.key}: ${yamlScalar(String(value))}`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Ask every wizard question (on the real terminal by default; tests inject
 * `io.question`). Empty input accepts the shown default; invalid input
 * re-asks.
 */
/**
 * The injection seam the tests use. Interactive runs pass nothing and the
 * wizard builds a readline interface over the real stdin/stdout.
 */
export interface WizardIo {
  input?: NodeJS.ReadableStream;
  output?: NodeJS.WritableStream;
  question?: (prompt: string) => Promise<string>;
}

export async function runInitWizard(io?: WizardIo) {
  const output = (io && io.output) || process.stdout;
  let question;
  let close = () => {};
  if (io && io.question) {
    question = io.question;
  } else {
    const rl = readline.createInterface({ input: (io && io.input) || process.stdin, output });
    question = (prompt) => rl.question(prompt);
    close = () => rl.close();
  }
  const answers = {};
  try {
    for (const field of WIZARD_FIELDS) {
      const def = field.def(answers);
      const choicesHint = field.choices ? ` (${field.choices.join("/")})` : "";
      const defHint = def === "" ? "none" : def;
      for (;;) {
        const raw = (await question(`${field.question}${choicesHint} [${defHint}]: `)).trim();
        const value = raw === "" ? def : raw;
        const error = validateAnswer(field, value);
        if (error === null) {
          answers[field.key] = value;
          break;
        }
        output.write(`✖ ${error}\n`);
      }
    }
  } finally {
    close();
  }
  return answers;
}
