# Runtime Environments

> Normative contract, generated by `csda init`. The environments below are the
> only ones this project recognises. Code must read its configuration from the
> environment — never hardcode a host, port, credential or database name.

## Environment catalog

| Environment | Purpose | Env file | Database |
| --- | --- | --- | --- |
| dev | Local development and day-to-day implementation | `.env.dev` | `{{DATABASE_NAME_DEV}}` |
| feature | Short-lived branch or preview validation | `.env.feature` | `{{DATABASE_NAME_FEATURE}}` |
| prod | Production-like configuration contract | `.env.prod` | `{{DATABASE_NAME_PROD}}` |

Declared environments: `{{ENVIRONMENTS}}`
Default environment: `{{DEFAULT_ENV}}`

The active environment is selected with `APP_ENV`. An unset `APP_ENV` means
`{{DEFAULT_ENV}}`.

## Database

- Engine: `{{DATABASE_ENGINE}}` (version `{{DATABASE_VERSION}}`)
- Application user: `{{DATABASE_USER}}`

| Environment | Host port | URL |
| --- | --- | --- |
| dev | `{{DATABASE_PORT_DEV}}` | `{{DATABASE_URL_DEV}}` |
| feature | `{{DATABASE_PORT_FEATURE}}` | `{{DATABASE_URL_FEATURE}}` |
| prod | `{{DATABASE_PORT_PROD}}` | `{{DATABASE_URL_PROD}}` |

Each environment binds a different host port so two of them can run side by
side. Inside the network every database listens on `{{DATABASE_CONTAINER_PORT}}`.

{{RUNTIME_DOCKER_SECTION}}

## Invariants

These hold for every environment. A change that breaks one is a defect, not a
configuration choice.

1. **No shared databases.** Each environment owns its own database name; the
   three above never point at the same instance.
2. **No credentials in the repository.** The generated `.env.*` files carry
   placeholders. Real secrets arrive from the deployment platform or a secret
   manager, never from a commit.
3. **No hardcoded configuration.** Hosts, ports, credentials and database names
   are read from the environment at runtime.
4. **`.env.example` is the schema.** Every variable the application reads must
   appear there, with a safe placeholder value.
5. **Adding an environment is a spec change.** Extend this document and the
   `.env.*` set together — a new environment that exists only in deployment
   configuration is drift.
