# Runtime Environments

> Normative contract, generated by `specgate init`. The environments below are the
> only ones this project recognises. Code must read its configuration from the
> environment — never hardcode a host, port or credential.

## Environment catalog

{{RUNTIME_ENV_TABLE}}

Declared environments: `{{ENVIRONMENTS}}`
Default environment: `{{DEFAULT_ENV}}`

The active environment is selected with `APP_ENV`. An unset `APP_ENV` means
`{{DEFAULT_ENV}}`.

{{RUNTIME_DATABASE_SECTION}}

{{RUNTIME_DOCKER_SECTION}}

## Invariants

These hold for every environment. A change that breaks one is a defect, not a
configuration choice.

{{RUNTIME_INVARIANTS}}
